# Generated by Django 2.0.2 on 2018-02-11 06:57

from django.db import migrations, models
import django.db.models.deletion
import promoapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('promoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promoapp.Ciudad'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=promoapp.utils.UploadToPathAndRename('uploads/')),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=promoapp.utils.UploadToPathAndRename('uploads/')),
        ),
    ]
